services:
  app:
    build: ../infra/dev/app/Dockerfile
    volumes:
      - ./:/E-Commerce-Chat-Microservice
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
    depends_on:
      - db

  db:
    build: ../infra/dev/db
    platform: linux/amd64
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/mysql_data:/var/lib/mysql

volumes:
  db_data:
